version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: compose-test_postgres_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"

  app:
    image: ghcr.io/xotmfrlox/cloud-native-devops-gcp:latest
    container_name: compose-test_app_1
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: compose-test_nginx_1
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
