version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"

  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: appdb
