apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - seulgichoi.dev
    - www.seulgichoi.dev
    secretName: devops-tls
  rules:
  - host: seulgichoi.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-app
            port:
              number: 80
